#---------------------------------------------------------------------------
# Darwin settings
CCFLAGS += -DOSX
LIB := libTensor.dylib
SHARED := -dynamiclib

JAVA_HOME ?= $(shell /usr/libexec/java_home)
# this is the subdirectory name in JAVA_HOME/include/ that contains platform-specific files
# it seems that some versions of Java 1.1 on linux need this to be "genunix"
JDKPLATFORMINCLUDESUBDIR := darwin
#---------------------------------------------------------------------------
